version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: exported
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
